language: node_js
node_js: node
branches: hexo
before_install:
- mkdir ~/.ssh
- openssl aes-256-cbc -K $encrypted_34447ae5b730_key -iv $encrypted_34447ae5b730_iv
  -in calil.enc -out ~\/.ssh/calil -d
- mv ~/.ssh/calil ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "calil"
- git config --global user.email calil@jingbei.li
install:
- npm install hexo-cli -g
- npm install
script:
- hexo generate
- hexo deploy
